#before_script:
#  - "rake vendor_test_gems"
#script: "sh -c 'test/test.sh'"
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - ruby-head
notifications:
  email: false
branches:
  only:
    - master
    - development
    - edge
bundler_args: --path vendor/bundle
