language: ruby
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
services:
  - mongodb
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
notifications:
  email: false
branches:
  only:
    - master
    - development
    - tests
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
