before_script:
  - "rake vendor_test_gems"
script: "rake"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - ruby-head
notifications:
  email: false
branches:
  only:
    - master
    - development
    - edge
#bundler_args: --path vendor/bundle
