language: ruby
before_install:
  - gem install bundler --pre
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "sh -c 'test/test.sh'"
services:
  - mongodb
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - ruby-head
  - jruby-head
notifications:
  email: false
branches:
  only:
    - master
    - development
    - adapters
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
