before_script:
  - "bundle exec rake db:drop db:create db:migrate"
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
notifications:
  email: false
branches:
  only:
    - master
    - development
    - edge
bundler_args: --path vendor/bundle
