before_script:
  - "sh -e /etc/init.d/xvfb start"
before_install:
  - gem install bundler
script: "sh -c 'export DISPLAY=:99.0 && test/test.sh'"
language: ruby
services:
  - mongodb
rvm:
  - 1.9.2
  - 1.9.3
notifications:
  email: false
branches:
  only:
    - master
    - development
    - adapters
#bundler_args: --path vendor/bundle
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
