before_script:
  - "sh -e /etc/init.d/xvfb start"
script: "sh -c 'export DISPLAY=:99.0 && test/test.sh'"
language: ruby
rvm:
  - 1.8.7
#  - ree
  - 1.9.2
  - 1.9.3
  - ruby-head
#  - jruby-18mode
#  - jruby-19mode
notifications:
  email: false
branches:
  only:
    - master
    - development
    - gem
#bundler_args: --path vendor/bundle
